"""
This type stub file was generated by pyright.
"""

"""Post-processing modules"""
modules = ...

def find(name):  # -> Any | None:
    """Return a postprocessor class with the given name"""
    ...

_cache = ...
