from .common import DownloaderBase

"""
This type stub file was generated by pyright.
"""

"""Downloader modules"""

modules = ...

def find(scheme: str) -> DownloaderBase | None:
    """Return downloader class suitable for handling the given scheme"""
    ...

_cache = ...
