from typing import Any

from ..job import DownloadJob
from ..path import PathFormat

"""
This type stub file was generated by pyright.
"""

"""Common classes and constants used by downloader modules."""

class DownloaderBase:
    """Base class for downloaders"""

    scheme = ...
    def __init__(self, job: DownloadJob) -> None: ...
    def config(self, key: str, default: Any = ...) -> Any:
        """Interpolate downloader config value for 'key'"""
        ...

    def download(self, url: str, pathfmt: PathFormat) -> bool:
        """Write data from 'url' into the file specified by 'pathfmt'"""
        ...
