from types import ModuleType

from .common import Extractor

"""
This type stub file was generated by pyright.
"""

modules = ...

def find(url: str) -> Extractor | None:
    """Find a suitable extractor for the given URL"""
    ...

def add[C](cls: C) -> C:
    """Add 'cls' to the list of available extractors"""
    ...

def add_module(module: ModuleType) -> list[Extractor]:
    """Add all extractors in 'module' to the list of available extractors"""
    ...

def extractors() -> list[Extractor]:
    """Yield all available extractor classes"""
    ...

_cache = ...
_module_iter = ...
